import type { Metadata } from "next";
import { Check, MessageCircle, Scissors } from "lucide-react";
import { whatsappLink } from "@/components/public-site";

export const metadata: Metadata = { title: "Tailoring", description: "Book bespoke tailoring, fittings, bridal, and occasion wear with RoseDen Atelier." };
export default function TailoringPage() {
  const services = ["Bespoke dresses and two-pieces", "Measurements and fitting appointments", "Bridal and occasion wear", "Alterations and fit refreshes", "Clear deposit and delivery planning"];
  return <main><section className="bg-burgundy px-4 py-20 text-white sm:px-6"><div className="mx-auto max-w-5xl"><Scissors className="text-gold" size={34} /><h1 className="mt-6 max-w-2xl font-display text-5xl font-semibold">Made for your body, your occasion, your confidence.</h1><p className="mt-5 max-w-xl leading-7 text-white/65">From first measurement to final fitting, RoseDen keeps the process personal and practical.</p></div></section><section className="mx-auto grid max-w-5xl gap-10 px-4 py-16 sm:px-6 md:grid-cols-2"><div><h2 className="font-display text-4xl font-semibold text-wine">How tailoring works</h2><div className="mt-7 space-y-4">{services.map((service) => <div key={service} className="flex gap-3 rounded-2xl bg-white p-4"><span className="grid h-8 w-8 shrink-0 place-items-center rounded-full bg-gold/15 text-gold"><Check size={17} /></span><p className="pt-1 text-sm font-medium">{service}</p></div>)}</div></div><div className="rounded-[32px] bg-wine p-8 text-white"><p className="text-xs font-bold uppercase tracking-wider text-gold">Book a consultation</p><h2 className="mt-3 font-display text-3xl font-semibold">Tell us what you want to create.</h2><p className="mt-4 leading-7 text-white/60">Send your inspiration, occasion date, location, and preferred appointment time. We will confirm the deposit and expected timeline.</p><a href={whatsappLink("Hello RoseDen Atelier, I would like to book a tailoring consultation.")} className="mt-8 flex h-13 items-center justify-center gap-2 rounded-full bg-gold font-semibold text-wine"><MessageCircle size={18} />Book on WhatsApp</a></div></section></main>;
}
