-- Phase 4A: automatic audit history.
-- Safe to run more than once.

create table if not exists public.audit_logs (
  id bigint generated by default as identity primary key,
  entity_type text not null,
  entity_id text,
  action text not null check (action in ('created', 'updated', 'deleted')),
  actor_id uuid references public.profiles(id) on delete set null,
  old_data jsonb,
  new_data jsonb,
  created_at timestamptz not null default now()
);

alter table public.audit_logs enable row level security;

do $$
begin
  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'audit_logs'
      and policyname = 'admins read audit logs'
  ) then
    create policy "admins read audit logs"
      on public.audit_logs
      for select
      to authenticated
      using (public.is_admin());
  end if;
end
$$;

create index if not exists audit_logs_created_at_idx
  on public.audit_logs (created_at desc);

create index if not exists audit_logs_entity_idx
  on public.audit_logs (entity_type, entity_id);

create or replace function public.record_audit_log()
returns trigger
language plpgsql
security definer
set search_path = public
as $function$
declare
  row_before jsonb;
  row_after jsonb;
  record_id text;
  audit_action text;
begin
  row_before := case when tg_op in ('UPDATE', 'DELETE') then to_jsonb(old) else null end;
  row_after := case when tg_op in ('INSERT', 'UPDATE') then to_jsonb(new) else null end;
  record_id := coalesce(row_after->>'id', row_before->>'id');
  audit_action := case tg_op
    when 'INSERT' then 'created'
    when 'UPDATE' then 'updated'
    when 'DELETE' then 'deleted'
  end;

  insert into public.audit_logs (
    entity_type,
    entity_id,
    action,
    actor_id,
    old_data,
    new_data
  )
  values (
    tg_table_name,
    record_id,
    audit_action,
    auth.uid(),
    row_before,
    row_after
  );

  return null;
end;
$function$;

do $$
declare
  table_name text;
begin
  foreach table_name in array array[
    'customers',
    'measurements',
    'orders',
    'order_items',
    'payments',
    'inventory',
    'inventory_stock_entries',
    'expenses',
    'post_batches',
    'business_settings'
  ]
  loop
    if to_regclass(format('public.%I', table_name)) is not null then
      execute format('drop trigger if exists audit_changes on public.%I', table_name);
      execute format(
        'create trigger audit_changes after insert or update or delete on public.%I for each row execute function public.record_audit_log()',
        table_name
      );
    end if;
  end loop;
end
$$;

revoke all on public.audit_logs from anon;
revoke insert, update, delete on public.audit_logs from authenticated;
grant select on public.audit_logs to authenticated;
